name: Releases

on: 
  push:
    tags:
    - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: k-paxian/dart-package-publisher@v1.3
        with:
          accessToken: ${{ secrets.FLUTTER_PUB_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.FLUTTER_PUB_REFRESH_TOKEN }}
      - uses: up9cloud/action-notify@master
        if: cancelled() == false
        env:
          GITHUB_JOB_STATUS: ${{ job.status }}
          TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
          TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
